const TITLES = [[1,"Iniciante"],[5,"Aventureiro"],[10,"Guerreiro"],[15,"Campeao"],[20,"Heroi"],[30,"Lendario"],[50,"Mitico"]];
const $ = (selector) => document.querySelector(selector);
const titleFor = (level) => TITLES.reduce((current, [minimum, title]) => Number(level) >= minimum ? title : current, "Iniciante");
const escapeHtml = (value) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
function toast(message) { const el = $("#toast"); el.textContent = message; el.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove("show"), 3500); }
function busy(button, active, text = "Salvando...") { if (!button) return; if (active) { button.dataset.label = button.textContent; button.textContent = text; button.disabled = true; } else { button.textContent = button.dataset.label || button.textContent; button.disabled = false; } }
async function loadHero() { try { const hero = await db.getHero(), exp = Number(hero.exp_atual), need = Number(hero.exp_necessaria); $("#exp-fill").style.width = `${Math.max(0, Math.min(100, Math.round(exp / need * 100)))}%`; $("#exp-val").textContent = `${exp} / ${need}`; $("#hero-class").textContent = `// ${titleFor(hero.nivel).toUpperCase()} - NV.${hero.nivel}`; $("#a-forca").textContent = hero.forca; $("#a-magia").textContent = hero.magia; $("#a-carisma").textContent = hero.carisma; $("#a-intel").textContent = hero.inteligencia; } catch (error) { toast(error.message); } }
function questHtml(quest) { const done = quest.status === "concluida", daily = quest.tipo === "diaria", label = quest.tipo === "principal" ? "Principal" : daily ? "Diaria" : "Side", klass = quest.tipo === "principal" ? "badge-main" : daily ? "badge-daily" : ""; return `<article class="quest-item ${done ? "done" : ""}"><div class="quest-main"><div class="quest-title">${escapeHtml(quest.nome)}</div><div class="quest-meta"><span class="badge ${klass}">${label}</span><span class="badge">${escapeHtml(quest.atributo[0].toUpperCase() + quest.atributo.slice(1))}</span><span class="badge ${done ? "badge-done" : "badge-pending"}">${done ? "Concluida" : "Pendente"}</span></div></div><div class="quest-actions"><button class="btn btn-complete" type="button" data-action="complete" data-id="${escapeHtml(quest.id)}" ${done ? "disabled" : ""}>${done ? "Feita" : "Concluir"}</button><button class="btn btn-delete" type="button" data-action="delete" data-id="${escapeHtml(quest.id)}" aria-label="Remover quest">X</button></div></article>`; }
async function loadQuests() { try { const quests = await db.getQuests(), daily = quests.filter((q) => q.tipo === "diaria"), active = quests.filter((q) => q.tipo !== "diaria" && q.status === "ativa"); $("#daily-summary").textContent = daily.length ? `${daily.filter((q) => q.status === "concluida").length}/${daily.length} concluidas hoje` : "Nenhuma diaria cadastrada ainda."; $("#daily-list").innerHTML = daily.length ? daily.map(questHtml).join("") : `<p class="state-text">Cadastre uma quest como diaria para ela aparecer aqui.</p>`; $("#quest-list").innerHTML = active.length ? active.map(questHtml).join("") : `<p class="state-text">Nenhuma quest ativa.</p>`; } catch (error) { $("#daily-list").innerHTML = $("#quest-list").innerHTML = `<p class="state-text">Erro ao carregar quests.</p>`; toast(error.message); } }
async function addQuest(event) { event.preventDefault(); const name = $("#q-nome").value.trim(), button = event.submitter; if (!name) return toast("Digite o nome da quest."); busy(button, true); try { await db.addQuest(name, $("#q-tipo").value, $("#q-atrib").value); $("#q-nome").value = ""; await loadQuests(); toast("Quest adicionada ao GitHub."); } catch (error) { toast(error.message); } finally { busy(button, false); } }
async function completeQuest(id, button) { busy(button, true); try { const result = await db.completeQuest(id); if (result.error) return toast(result.error); await Promise.all([loadHero(), loadQuests()]); toast(result.levelUp ? `Level up! NV.${result.nivel}` : `+${result.expGanho} EXP`); } catch (error) { toast(error.message); } finally { busy(button, false); } }
async function deleteQuest(id, button) { if (!confirm("Remover esta quest?")) return; busy(button, true); try { const result = await db.deleteQuest(id); if (result.error) return toast(result.error); await loadQuests(); toast("Quest removida do GitHub."); } catch (error) { toast(error.message); } finally { busy(button, false); } }
async function resetDailies(button) { busy(button, true); try { const result = await db.resetDailies(); await loadQuests(); toast(result.resetCount ? `${result.resetCount} diaria(s) resetada(s).` : "Diarias ja estavam pendentes."); } catch (error) { toast(error.message); } finally { busy(button, false); } }
function formatDate(value) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("pt-BR", { day:"2-digit", month:"2-digit", year:"2-digit", hour:"2-digit", minute:"2-digit" }).format(date); }
async function loadHistory() { try { const rows = await db.getHistorico(); $("#hist-list").innerHTML = rows.length ? rows.slice(0,50).map((item) => `<article class="history-item"><div class="history-title">${escapeHtml(item.acao)}</div><div class="history-meta"><span class="badge">+${item.exp_ganho} EXP</span><span class="badge">+${item.pontos} ${escapeHtml(item.atributo.toUpperCase())}</span><span class="badge">NV.${item.nivel_atual}</span><span class="badge">${escapeHtml(formatDate(item.data))}</span></div></article>`).join("") : `<p class="state-text">Nenhum registro ainda.</p>`; } catch (error) { toast(error.message); } }
async function exportData() { try { const url = URL.createObjectURL(new Blob([JSON.stringify(await db.exportAll(), null, 2)], { type: "application/json" })), link = document.createElement("a"); link.href = url; link.download = `rpg-backup-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(url); toast("Backup exportado."); } catch (error) { toast(error.message); } }
function importData() { const input = document.createElement("input"); input.type = "file"; input.accept = ".json"; input.onchange = async () => { if (!input.files[0]) return; try { const result = await db.importAll(JSON.parse(await input.files[0].text())); if (result.error) return toast(result.error); await Promise.all([loadHero(), loadQuests()]); toast("Dados importados para o GitHub."); } catch (error) { toast(error.message || "Arquivo JSON invalido."); } }; input.click(); }
async function resetData() { if (!confirm("ATENCAO: Isso apagara TODOS os dados do GitHub. Deseja continuar?")) return; try { await db.resetAll(); await Promise.all([loadHero(), loadQuests()]); toast("Dados resetados no GitHub."); } catch (error) { toast(error.message); } }
function tokenStatus() { $("#github-token-status").textContent = db.hasToken() ? "Token configurado neste navegador. Alteracoes serao salvas no GitHub." : "Token nao configurado: voce pode consultar os dados, mas nao salvar alteracoes."; }
function showTab(name) { document.querySelectorAll(".tab").forEach((tab) => tab.classList.toggle("active", tab.dataset.tab === name)); document.querySelectorAll(".tab-panel").forEach((panel) => panel.classList.toggle("active", panel.id === `tab-${name}`)); if (name === "historico") loadHistory(); }
function bind() { $("#quest-form").addEventListener("submit", addQuest); $("#btn-reset-dailies").onclick = (event) => resetDailies(event.currentTarget); $(".tabs").onclick = (event) => { const tab = event.target.closest("[data-tab]"); if (tab) showTab(tab.dataset.tab); }; document.body.onclick = (event) => { const button = event.target.closest("[data-action]"); if (!button) return; if (button.dataset.action === "complete") completeQuest(button.dataset.id, button); else deleteQuest(button.dataset.id, button); }; $("#btn-export").onclick = exportData; $("#btn-import").onclick = importData; $("#btn-reset-data").onclick = resetData; $("#btn-save-token").onclick = () => { db.setToken($("#github-token").value); $("#github-token").value = ""; tokenStatus(); toast(db.hasToken() ? "Token salvo somente neste navegador." : "Token removido deste navegador."); }; }
async function init() { bind(); tokenStatus(); try { await db.init(); await Promise.all([loadHero(), loadQuests()]); } catch (error) { toast(error.message); } }
init();
